export const ADD_TASK = 'ADD_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const CHANGE_SORT_FIELD = 'CHANGE_SORT_FIELD';
export const CHANGE_SORT_DIRECTION = 'CHANGE_SORT_DIRECTION';
export const CHANGE_ADD_MODAL_STATE = 'CHANGE_ADD_MODAL_STATE';